on:
    push:
        branches:
            - "master"
    schedule:
        - cron: '0 14 * * *'

jobs:
    docker-redis:
        runs-on: self-hosted
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Checkout submodules
                run: git submodule update --init --recursive
            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            - 
                name: Build and push redis:unstable
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    tags: k0d3r1s/redis:unstable
                    platforms: linux/amd64
